// <auto-generated />
using System;
using AniDrop.DBInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AniDrop.Migrations
{
    [DbContext(typeof(AniDropDBContext))]
    [Migration("20260722064318_FixRollHistory")]
    partial class FixRollHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AniDrop.Domain.AnimeTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodesNum")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnimeTitles");
                });

            modelBuilder.Entity("AniDrop.Domain.PoolItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnimeTitleId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TierListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimeTitleId");

                    b.HasIndex("PoolId");

                    b.HasIndex("TierListId");

                    b.ToTable("PoolItems");
                });

            modelBuilder.Entity("AniDrop.Domain.RollHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PoolItem")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoolItem");

                    b.HasIndex("UserId");

                    b.ToTable("RollHistory");
                });

            modelBuilder.Entity("AniDrop.Domain.ShikimoriProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShikimoriId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("ShikimoriProfiles");
                });

            modelBuilder.Entity("AniDrop.Domain.TierList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DropChance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.ToTable("TierLists");
                });

            modelBuilder.Entity("AniDrop.Domain.TitlePool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TitlePools");
                });

            modelBuilder.Entity("AniDrop.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AniDrop.Domain.PoolItem", b =>
                {
                    b.HasOne("AniDrop.Domain.AnimeTitle", "AnimeTitle")
                        .WithMany()
                        .HasForeignKey("AnimeTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniDrop.Domain.TitlePool", "Pool")
                        .WithMany("PoolItems")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniDrop.Domain.TierList", "Tier")
                        .WithMany()
                        .HasForeignKey("TierListId");

                    b.Navigation("AnimeTitle");

                    b.Navigation("Pool");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("AniDrop.Domain.RollHistory", b =>
                {
                    b.HasOne("AniDrop.Domain.PoolItem", "PoolItemNavigation")
                        .WithMany()
                        .HasForeignKey("PoolItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniDrop.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoolItemNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AniDrop.Domain.ShikimoriProfile", b =>
                {
                    b.HasOne("AniDrop.Domain.User", null)
                        .WithOne("ShikimoriProfile")
                        .HasForeignKey("AniDrop.Domain.ShikimoriProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniDrop.Domain.TierList", b =>
                {
                    b.HasOne("AniDrop.Domain.TitlePool", "Pool")
                        .WithMany("TierLists")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("AniDrop.Domain.TitlePool", b =>
                {
                    b.Navigation("PoolItems");

                    b.Navigation("TierLists");
                });

            modelBuilder.Entity("AniDrop.Domain.User", b =>
                {
                    b.Navigation("ShikimoriProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
